### ISSUE TITLE
A question for your project

### ISSUE THREAD

**Issue by Riofd** [maxxxzdn/GNNExplainer#1]
Hello, thank you for your fantastic work! But I have a question when I use your code, can you tell me about the structure of your neural networks? If you can provide a simple example, that may help me a lot. Thank you!

**Comment by Riofd** [comment]
My model is :
`

class Net(torch.nn.Module):

    def __init__(self, args):
        super(Net, self).__init__()
        self.args = args
        self.pooling_ratio = args.pooling_ratio
        self.nhid = args.nhid
        self.dropout_ratio = args.dropout_ratio
        self.conv1 = GCNConv(dataset.num_features, self.nhid)
        self.pool1 = SAGPooling(self.nhid, ratio=self.pooling_ratio)
        self.bn1 = nn.BatchNorm1d(self.nhid, eps=1e-05, momentum=0.1, affine=True)
        self.conv2 = GCNConv(self.nhid, self.nhid)
        self.pool2 = SAGPooling(self.nhid, ratio=self.pooling_ratio)
        self.conv3 = GCNConv(self.nhid, self.nhid)
        self.pool3 = SAGPooling(self.nhid, ratio=self.pooling_ratio)
        self.lin1 = nn.Linear(self.nhid, self.nhid)
        self.lin2 = nn.Linear(self.nhid, self.nhid//2)
        self.lin3 = nn.Linear(self.nhid//2, dataset.num_classes)

    def forward(self, data):
        x, edge_index, batch = data.x, data.edge_index, data.batch
        x = F.relu(self.conv1(x, edge_index))
        x = F.relu(self.conv2(x, edge_index))
        x = F.relu(self.conv3(x, edge_index))
        x = self.bn1(x)
        x, _ = scatter_max(x, data.batch, dim=0)
        x = F.relu(self.lin1(x))
        x = F.dropout(x, p=self.dropout_ratio, training=self.training)
        x = F.relu(self.lin2(x))
        x = F.dropout(x, p=self.dropout_ratio, training=self.training)
        x = self.lin3(x)
        # x = F.log_softmax(self.lin3(x), dim=-1)
        return x
`
And when I use GNNExplainer:

`
explainer = GNNExplainer(model, epochs=200)
edge_mask = explainer.explain_graph(x=x, edge_index=edge_index, batch=data.batch)
`

And it suffers error:
Traceback (most recent call last):
  File "D:/Users/zrf/zdsw/WECC.py", line 295, in <module>
    test_acc, top2_acc, test_loss = test(testloader)
  File "D:/Users/zrf/zdsw/WECC.py", line 200, in test
    edge_mask = explainer.explain_graph(x=x, edge_index=edge_index, batch=data.batch)
  File "D:\Users\zrf\zdsw\GNNExplainer.py", line 217, in explain_graph
    log_logits = self.model(x=x, edge_index=edge_index, **kwargs)
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'x'

**Comment by maxxxzdn** [comment]
Hi! Thank you for your kind words. 
It seems like your forward method takes data argument as the only input. However, pytorch geometric implementation of GNNExplainer calculates model predictions in the following way: 

> log_logits = self.model(x=x, edge_index=edge_index, **kwargs)

Hence I suggest you using the explain_graph method with data.x and data.edge_index along with data argument for your network. It could look the following way: 

> edge_mask = explainer.explain_graph(x=data.x, edge_index=data.edge_index, data=data)

Or you can change input arguments for your networks such that it gets x and edge_index directly.  
Please find the model I used along with the explainer here:
https://github.com/maxxxzdn/EEGCN/blob/main/model.py

**Comment by Riofd** [comment]
> Hi! Thank you for your kind words.
> It seems like your forward method takes data argument as the only input. However, pytorch geometric implementation of GNNExplainer calculates model predictions in the following way:
> 
> > log_logits = self.model(x=x, edge_index=edge_index, **kwargs)
> 
> Hence I suggest you using the explain_graph method with data.x and data.edge_index along with data argument for your network. It could look the following way:
> 
> > edge_mask = explainer.explain_graph(x=data.x, edge_index=data.edge_index, data=data)
> 
> Or you can change input arguments for your networks such that it gets x and edge_index directly.
> Please find the model I used along with the explainer here:
> https://github.com/maxxxzdn/EEGCN/blob/main/model.py

Thank you for your help! It works well now.
